import { ModelFactory } from "webiny/api/cms/model";

/**
 * Minimal Product model for the demo. The "Generate AI summary" bulk action writes
 * `aiSummary` and stamps `aiSummarizedRun` (the per-run token that drives convergence).
 */
class ProductModelImpl implements ModelFactory.Interface {
    async execute(builder: ModelFactory.Builder) {
        return [
            builder
                .public({ modelId: "product", name: "Product", group: "ungrouped" })
                .description("Demo products for the Generate AI summary bulk action.")
                .fields(fields => ({
                    name: fields
                        .text()
                        .renderer("textInput")
                        .label("Name")
                        .required("Name is required"),
                    description: fields.longText().renderer("textarea").label("Description"),
                    aiSummary: fields
                        .longText()
                        .renderer("textarea")
                        .label("AI summary")
                        .help('Generated by the "Generate AI summary" bulk action.'),
                    aiSummarizedRun: fields
                        .text()
                        .renderer("textInput")
                        .label("AI summary run")
                        .help(
                            "Internal: the last run token that summarized this product. Lets the background task converge while still allowing re-runs."
                        )
                }))
                .layout([["name"], ["description"], ["aiSummary"], ["aiSummarizedRun"]])
                .titleFieldId("name")
                .singularApiName("Product")
                .pluralApiName("Products")
        ];
    }
}

export const ProductModel = ModelFactory.createImplementation({
    implementation: ProductModelImpl,
    dependencies: []
});
